build_from:
  aarch64: alpine:3.19
  armv7: alpine:3.19
  amd64: alpine:3.19
labels:
  io.hass.name: "n8n with FFmpeg"
  io.hass.description: "n8n automation tool with FFmpeg support"
  io.hass.type: addon
  io.hass.version: 1.0.2
args:
  TEMPIO_VERSION: "2021.09.0"